Python Basics

**Assigning variables**


In Python we use variables to assign content to them that we want to use later. 

*   The syntax is: variable_name = value

value can be many things, which we will learn little by little. 

Let's assign a few variables next:

In [ ]:
var_1 = 3
var_2 = 6
variable_3 = 10
variable_4 = 20

We can access its content just by typing the variable name in a cell and running the cell:

In [ ]:
var_1

In [ ]:
variable_4

If I try to call a variable that I haven't assigned, it will throw me an error:

In [ ]:
warner_variable

Likewise, if I write an assignment, but don't run the cell, that variable won't be available to me later:

In [ ]:
var_5 = 66

In [ ]:
var_5

**Numerical operations**

We have been assigning numbers to variables. In Python we can perform mathematical operations in a very simple way. We simply have to use the arithmetic operators that we already know to do operations between the variables that we have previously defined. The arithmetic operators in Python are the following:


*   Addition          +
*   Subtraction       -
*   Multiplication    *
*   Division          /
*   Exponentiation    **

Let's first assign some variables:

In [ ]:
var_1 = 4
var_2 = 54
var_3 = 23
var_4 = 89


To perform numerical operations with these variables, simply write the operation in a cell and run it. We will see the result as output below the cell:

In [ ]:
var_1 + var_2

In [ ]:
var_2 - var_4

In [ ]:
var_3 * var_1

In [ ]:
var_4 / var_2
var_2 ** var_1

8503056

If we want to print more than one operation in the same cell, we can use the print function:

In [ ]:
print(var_1 + var_2)
print(var_3 - var_4)
print(var_2 * var_2)

We can also assign the results of our operations to other variables:

In [ ]:
result_sum = var_1 + var_3

result_sum

Could we add string variables?

In [ ]:
st_1 = "Python Course"
st_2 = " rocks"
st_1 + st_2

'Python Course rocks'

**DATA TYPE**

Python has different data types to represent different things. At the moment we are going to learn the 4 most basic and essential:


*   int => integers
*   float => decimal numbers
*   string => sequences of characters (text)
*   boolean => booleans (True or False)

In [ ]:
# This is an integer

var_int = 4598

print(var_int)
print(type(var_int))
print("\n")

# This is a decimal

var_float = 369.432

print(var_float)
print(type(var_float))
print("\n")

# This is a string

var_string = "Soy una string"

print(var_string)
print(type(var_string))
print("\n")

# This is a boolean

var_bool = True

print(var_bool)
print(type(var_bool))
print("\n")

**String Interpolation**


Later we will see that Strings can contain very relevant information within our data sets (such as names of people, descriptions of processes, categories, etc). For now, we are going to use our Strings to print annotations on our outputs

In [ ]:
var_1 = 15.3
var_2 = 23.4

print("Suma de var_1 y var_2")
print(var_1 + var_2)

But sometimes it is necessary or desirable to interpolate the value of the variable within that string. For that we use the so-called f-strings. The format of an f-string is as follows:

*   f"This is text {this_is_a_variable} this is more text"

In [ ]:
var_3 = 43
var_4 = 24.3

sum_1 = var_3 + var_4

print(f'The sum of var_3  and var_4 is: {sum_1}')

The sum of var_3  and var_4 is: 67.3

Or you can even do something like this:

In [ ]:
print(f'The sum of {var_3} and {var_4} is: {var_3 + var_4}')

**Booleans and comparison operators**

We already practiced with ints, floats and strings. We just need to understand what to use booleans for. Our programs need a way to "make decisions." In real life, we usually make decisions by making comparisons between the options and making the decision that best suits us taking into account the context. The first step in achieving this is the comparison operators. They are used to compare values. They return a boolean True when the comparison is true and a boolean False when the comparison is false.

Python has the following comparison operators:


*   Greater than: >  
*   Same as: ==
*   Not equal (different) than: !=
*   Less than or equal to: <=

In [ ]:
var_1 = 34
var_2 = 12
var_3 = 23.24
var_4 = 23.56
var_5 = "OK"
var_6 = "ERROR"
var_7 = True
var_8 = False

Now let's look at some comparisons to see how our operators perform.

In [ ]:
var_1 > var_2

In [ ]:
var_3 < var_4

In [ ]:
var_5 == var_6

In [ ]:
var_5 != var_8

**Logical Operators**

Logical operators allow us to join two comparison statements

*   And
*   Or
*   Not

AND

Many times a single comparison statement will not be enough to filter the data as we want. In that case, **and** can help us join two statements. and returns True when both statements return True.

In [ ]:
var_1 = 128
var_2 = 328
var_3 = 212
var_4 = 543

In [ ]:
var_4> var_3 and var_1>= var_2

In [ ]:
var_4 < var_2 and var_3 < var_2

**OR**

**Or** is very similar to and. It also helps us to join two comparison statements and obtain a new result. The difference is that **or** returns True when either or both comparisons return True

In [ ]:
var_1 = 128
var_2 = 328
var_3 = 212
var_4 = 543

In [ ]:
var_4> var_3 or var_1 < var_2

In [ ]:
var_4 < var_2 or var_3 < var_4

**NOT** 

**Not** simply returns the boolean opposite of the one it receives

In [ ]:
not(True)

False

In [ ]:
not(not(False))

False

In [ ]:
not((var_4> var_3 or var_1 < var_2) and (var_4 < var_2 or var_3 < var_4))