**HOMEWORK #1**

**ACTIVITY 1**

Here are some assigned variables:

In [ ]:
name_1 = "Jenny"
name_2 = "Frame P."

age_1 = 110
age_2 = 42

star_1 = "Woopsie Doopsies"
star_2 = "Omega-3"
star_3 = "Justin Bieber"
star_4 = "The Twinkle"
star_5 = "Rosebert"

total_names_of_stars_mentioned = 5
number_of_desired_stars = 325

Using ALL of the variables above, create one (or more) strings that, running the cell, print the following history:

"Marco P. and Jenny are great friends. The best of them. They have been going back and forth for decades. Yes, decades. Marco P. is 110 years old and Jenny is 42. If you add up their ages, you get 152, which curiously is the number of stars that Marco P. and Jenny have named together. Their stars are their biggest fascination. They bought them at Best Buy in a celestial object bargain. There's 'Woopsie Doopsies', 'Omega-3', 'Justin Bieber', 'The Twinkle' , 'Rosaberta' and 147 other stars. Marco P. and Jenny plan to survive until the 22nd century. How many more stars will they have to buy and name together! Their goal is 325. Only 173 to go. Come on Marco P. and Jenny Marco P. and Jenny are the best of friends. There is no doubt about it."

Remember to use ALL the variables we have assigned. Also, all numbers that appear in the text must be interpolated variables or arithmetic operations. No number can be a simple string.

In [ ]:
# INSERT CODE

**ACTIVITY 2**

Here are some variables that have been assigned:

In [ ]:
var_1 = 3
var_2 = 5
var_3 = 9
var_4 = 1
var_5 = 9
var_6 = -6
var_7 = 5
var_8 = 4

Below you have some comparisons that are incomplete, along with the expected result of said comparison. Add the appropriate comparison operators, in the middle of the variables, so that when running the cells the expected Results are obtained. For this challenge, the operators == and != are not allowed.

In [ ]:
var_1 var_3 # Expected result: False

In [ ]:
var_1 var_4 # Expected result: True

In [ ]:
var_2 var_7 # Expected result: True

In [ ]:
var_8 var_6 # Expected result: True

In [ ]:
var_3 var_5 # Expected result: False

In [ ]:
var_1 var_3 # Expected result: True

**ACTIVITY 3**

Here are some variables that have been assigned:

In [ ]:
var_1 = 3
var_2 = 5
var_3 = 9
var_4 = 1
var_5 = 9
var_6 = -6
var_7 = 5
var_8 = 4

We have some logic comparisions. Before you run the cell, try to guess which will be the expect result. In one cell, there will be a problem in the code, fix it!

In [ ]:
not(var_1<var_4)

In [ ]:
(var_3>var_5) and  (var_8 == var_6)

In [ ]:
not(var_7<var_4) or (var_8 != var_8)

In [ ]:
var_9 > var_7